name: Deploy on Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/final-project:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/final-project:${{ github.sha }}

 
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/final_project
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/final-project-web:latest
            if [ ! -f /opt/final_project/docker-compose.yml ]; then
              curl -sO https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.prod.yml -o /opt/final_project/docker-compose.yml
            fi
            cd /opt/final_project
            docker-compose down
            docker-compose up -d --remove-orphans
            docker image prune -f